### ISSUE TITLE
Do you have the Skywalker Apk

### ISSUE THREAD

**Issue by jaykay1967** [0x4f53/classy-watch-pack#1]
i cant see the X-33 file

**Comment by 0x4f53** [comment]
Hey, I'm still designing it. I forgot to get rid of it from the Markdown. What I am having a problem with is finding the font online.

**Comment by jaykay1967** [comment]
Thanks for responding.As you will know a few years back there was an app for previous versions of wear os (or maybe tizen). I saw mention of samsung watchface designer software but i have never used that.I located two bin files online. Are they any use to you? Can you convert the files into something you can extract the fonts from?Best wishes Jay KennyFrom: Owais Shaikh ***@***.***>Sent: Thursday, August 24, 2023 1:18:54 PMTo: 0x4f53/classy-watch-pack ***@***.***>Cc: jaykay1967 ***@***.***>; Author ***@***.***>Subject: Re: [0x4f53/classy-watch-pack] Do you have the Skywalker Apk (Issue
 #1)
Hey, I'm still designing it. I forgot to get rid of it from the Markdown. What I am having a problem with is finding the font online.

**Comment by 0x4f53** [comment]
Sure, link them to me. I would also like the contact information of the creators of that bin file so that I can credit them. Thanks.

**Comment by jaykay1967** [comment]
Their is a galaxy watch designer (gwd) file in this thread for downloadhttps://forum.xda-developers.com/t/download-the-omega-speedmaster-x-33-skywalker-watchface.4126089/Best wishes Jay Kenny

**Comment by 0x4f53** [comment]
Done, #2 is ready. You'll notice that the luminova hands don't work like the real deal. It's because Watchface Studio doesn't have ambient brightness sensor data. I already [raised a request on Samsung Developers](https://forum.developer.samsung.com/t/wfs-feature-requests-q3-2023/25431/105?u=0x4f53), let's see what they say.

**Comment by jaykay1967** [comment]
Cheers.On my way home.  Will be able to test in an hour.Best wishes Jay Kenny

**Comment by jaykay1967** [comment]
Thank you so much.JayBest wishes Jay Kenny
